language: node_js
notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/458454925190627338/VfvfihEs3v_Iy7E6HzoQ-qlpUl8qmLxKRmXIG9bOTLOCdMePOHLGZvza_dhRHLQHTFVC
node_js:
  - "8.1"
  - "lts/*"
  - "node"
env:
  global:
    - SKIP_SASS_BINARY_DOWNLOAD_FOR_CI = true
script:
  - npm rebuild node-sass --force
  - yarn build