[[headers]]

    for = "/*"

    [headers.values]
        X-Frame-Options = "DENY"
        X-Content-Type-Options: nosniff
        X-XSS-Protection = "1; mode=block"
        Content-Security-Policy = "frame-ancestors https://nightly.cloudcite.net
        Access-Control-Allow-Origin = "https://cloudcite.net"